# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubActions' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubActions
  pod 'SwiftLint'

  target 'GitHubActionsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubActionsUITests' do
    # Pods for testing
  end

end
